import { json, prisma } from './db.ts';

async function seed() {
  console.log('Seeding data...');

  // Create sample tenant (api_key is generated by the database default)
  const tenant = await prisma.tenant.upsert({
    where: { slug: 'demo' },
    update: {},
    create: { slug: 'demo', name: 'Demo Project' },
    select: { id: true, apiKey: true },
  });
  console.log(`Tenant: ${tenant.id} (API key: ${tenant.apiKey})`);

  // Create sample agents
  const agentNames = ['main', 'feat-auth', 'feat-ui'];
  for (const name of agentNames) {
    await prisma.agent.upsert({
      where: { tenantId_name: { tenantId: tenant.id, name } },
      update: {},
      create: { tenantId: tenant.id, name },
    });
  }

  // Create sample tasks with rich JSONB data
  const sampleTasks = [
    {
      summary: 'Add CSV export to leave report',
      module: 'backend/src/routes/leaves.ts',
      status: 'done',
      agent: 'main',
      project: 'team-management',
      branch: 'feat/csv-export',
      started_at: '2026-07-04T09:00:00Z',
      ended_at: '2026-07-04T11:30:00Z',
      progress_log: [
        { at: '2026-07-04T09:00:00Z', note: 'Wrote CSV generator function', by: 'main' },
        { at: '2026-07-04T10:15:00Z', note: 'Blocked — date format unclear', by: 'main' },
        { at: '2026-07-04T11:30:00Z', note: 'Done. Shipped behind feature flag.', by: 'main' },
      ],
      files_changed: ['backend/src/routes/leaves.ts', 'backend/src/services/csv.ts'],
    },
    {
      summary: 'Refactor Teams page sidebar',
      module: 'frontend/src/pages/Teams.tsx',
      status: 'in_progress',
      agent: 'main',
      project: 'team-management',
      branch: 'feat/teams-sidebar',
      started_at: '2026-07-05T14:00:00Z',
      progress_log: [
        {
          at: '2026-07-05T14:00:00Z',
          note: 'Extracted sidebar into separate component',
          by: 'main',
        },
        { at: '2026-07-05T15:30:00Z', note: 'Working on responsive breakpoints', by: 'main' },
      ],
      files_changed: ['frontend/src/pages/Teams.tsx', 'frontend/src/components/Sidebar.tsx'],
    },
    {
      summary: 'Set up auth middleware',
      module: 'backend/src/middleware/auth.ts',
      status: 'done',
      agent: 'feat-auth',
      project: 'team-management',
      branch: 'feat/auth',
      started_at: '2026-07-03T10:00:00Z',
      ended_at: '2026-07-03T16:00:00Z',
      progress_log: [
        { at: '2026-07-03T10:00:00Z', note: 'Implemented JWT verification', by: 'feat-auth' },
        { at: '2026-07-03T14:00:00Z', note: 'Added RBAC checks', by: 'feat-auth' },
        { at: '2026-07-03T16:00:00Z', note: 'Done. Tests passing.', by: 'feat-auth' },
      ],
      files_changed: ['backend/src/middleware/auth.ts', 'backend/src/middleware/rbac.ts'],
      ai_provider: 'anthropic/claude-4',
    },
    {
      summary: 'Design system color tokens',
      module: 'frontend/src/styles/tokens.css',
      status: 'blocked',
      agent: 'feat-ui',
      project: 'team-management',
      branch: 'feat/design-tokens',
      started_at: '2026-07-04T08:00:00Z',
      progress_log: [
        { at: '2026-07-04T08:00:00Z', note: 'Researched accessible color palette', by: 'feat-ui' },
        {
          at: '2026-07-04T10:00:00Z',
          note: 'Blocked — waiting for design approval',
          by: 'feat-ui',
        },
      ],
      files_changed: ['frontend/src/styles/tokens.css'],
    },
  ];

  for (const task of sampleTasks) {
    const created = await prisma.task.create({
      data: {
        tenantId: tenant.id,
        data: json(task),
        status: task.status,
        agentName: task.agent,
        module: task.module ?? null,
        project: task.project ?? null,
        startedAt: task.started_at ? new Date(task.started_at) : null,
        endedAt: task.ended_at ? new Date(task.ended_at) : null,
      },
    });

    // Log task_start activity
    await prisma.activityLog.create({
      data: {
        tenantId: tenant.id,
        taskId: created.id,
        agentName: task.agent,
        action: 'task_start',
        data: json({ summary: task.summary }),
      },
    });

    for (const progress of task.progress_log) {
      await prisma.activityLog.create({
        data: {
          tenantId: tenant.id,
          taskId: created.id,
          agentName: progress.by,
          action: 'task_progress',
          data: json({ note: progress.note }),
        },
      });
    }

    if (task.status === 'done') {
      await prisma.activityLog.create({
        data: {
          tenantId: tenant.id,
          taskId: created.id,
          agentName: task.agent,
          action: 'task_end',
          data: json({ summary: task.summary }),
        },
      });
    }
  }

  console.log(`Seeded ${sampleTasks.length} sample tasks with activity log.`);

  // Developers + open session + locks (governance P0 demo)
  const garry = await prisma.developer.upsert({
    where: { tenantId_name: { tenantId: tenant.id, name: 'Garry Agum' } },
    update: {},
    create: { tenantId: tenant.id, name: 'Garry Agum', githubUser: 'garry-kinetic' },
  });
  const leo = await prisma.developer.upsert({
    where: { tenantId_name: { tenantId: tenant.id, name: 'Leo Dizon' } },
    update: {},
    create: { tenantId: tenant.id, name: 'Leo Dizon', githubUser: 'leokinetic' },
  });

  const existingOpen = await prisma.devSession.findFirst({
    where: { tenantId: tenant.id, status: 'open' },
  });
  if (!existingOpen) {
    const session = await prisma.devSession.create({
      data: {
        tenantId: tenant.id,
        number: 1,
        developerId: garry.id,
        module: 'Booking Management',
        branch: 'dev/garry-kinetic/booking',
        status: 'open',
        plan: json([
          'Wire orientation history startup migration',
          'Release Contract Module locks',
        ]),
      },
    });
    await prisma.sessionRequirement.createMany({
      data: [
        {
          sessionId: session.id,
          reqId: 'REQ-001-001',
          description: 'Wire orientation history DDL into startup',
          status: 'complete',
          proof: json({
            file: 'backend/startup_migrations.py',
            function: 'run_startup_migrations',
            trace: 'app start → ensure_booking_orientation_history_table',
          }),
        },
        {
          sessionId: session.id,
          reqId: 'REQ-001-002',
          description: 'Browser QA: TM Orientation History list',
          status: 'deferred',
        },
      ],
    });
    await prisma.fileLock.create({
      data: {
        tenantId: tenant.id,
        path: 'backend/startup_migrations.py',
        category: 'CORE',
        developerId: garry.id,
        sessionId: session.id,
        branch: 'dev/garry-kinetic/booking',
        notes: 'Additive orientation history hook',
      },
    });
    await prisma.fileLock.create({
      data: {
        tenantId: tenant.id,
        path: 'frontend/src/App.jsx',
        category: 'CORE',
        developerId: leo.id,
        branch: 'dev/leokinetic/overtime-module',
        notes: 'Additive overtime routes — coordinate before edit',
      },
    });
    console.log('Seeded sample developers, open session #1, and file locks.');
  }

  console.log(`\nDemo tenant API key: ${tenant.apiKey}`);
  console.log(`Try: curl -H "Authorization: Bearer ${tenant.apiKey}" http://localhost:3001/sessions?status=open`);
  console.log(`MCP:  http://localhost:3001/mcp  (Authorization: Bearer <api-key>)`);

  await prisma.$disconnect();
}

await seed();
