import { Hono } from 'hono';
import { json, prisma } from '../db.ts';
import { adminMiddleware } from '../_middleware/admin.ts';
import { CreateTenantSchema } from './tenants.schema.ts';
import type { TenantRow } from './tenants.schema.ts';

const tenants = new Hono();

// All tenant-management routes are admin-only (shared ADMIN_TOKEN Bearer).
tenants.use('*', adminMiddleware);

// GET /tenants — list all tenants (admin)
tenants.get('/', async (c) => {
  const rows = await prisma.tenant.findMany({
    select: { id: true, slug: true, name: true, createdAt: true },
    orderBy: { createdAt: 'desc' },
  });
  return c.json({
    items: rows.map((t) => ({
      id: t.id,
      slug: t.slug,
      name: t.name,
      created_at: t.createdAt.toISOString(),
    })),
  });
});

// POST /tenants — create a new tenant (admin). The API key is generated by the
// DB (pgcrypto) and returned in plaintext this one time only.
tenants.post('/', async (c) => {
  const body = CreateTenantSchema.parse(await c.req.json());

  const existing = await prisma.tenant.findUnique({
    where: { slug: body.slug },
    select: { id: true },
  });
  if (existing) return c.json({ error: 'Tenant with this slug already exists' }, 409);

  const tenant = await prisma.tenant.create({
    data: {
      slug: body.slug,
      name: body.name,
      config: json(body.config ?? {}),
    },
    select: { id: true, slug: true, name: true, apiKey: true, createdAt: true },
  });

  const row: TenantRow = {
    id: tenant.id,
    slug: tenant.slug,
    name: tenant.name,
    api_key: tenant.apiKey,
    config: {},
    created_at: tenant.createdAt.toISOString(),
  };
  return c.json(row, 201);
});

// GET /tenants/:id — get tenant info (admin)
tenants.get('/:id', async (c) => {
  const tenant = await prisma.tenant.findUnique({
    where: { id: c.req.param('id') },
    select: { id: true, slug: true, name: true, createdAt: true },
  });
  if (!tenant) return c.json({ error: 'Tenant not found' }, 404);
  return c.json({
    id: tenant.id,
    slug: tenant.slug,
    name: tenant.name,
    created_at: tenant.createdAt.toISOString(),
  });
});

// DELETE /tenants/:id — delete a tenant (admin). Cascades to all related data
// (agents, tasks, sessions, locks, activity) per the schema's onDelete: Cascade.
tenants.delete('/:id', async (c) => {
  try {
    await prisma.tenant.delete({ where: { id: c.req.param('id') } });
  } catch (err: unknown) {
    // Prisma P2025 = record not found
    if (typeof err === 'object' && err !== null && 'code' in err && err.code === 'P2025') {
      return c.json({ error: 'Tenant not found' }, 404);
    }
    throw err;
  }
  return c.json({ deleted: c.req.param('id') });
});

export { tenants };
